### ISSUE TITLE
Error in pulling 7.2 image in Gitlab pipeline

### ISSUE THREAD

**Issue by xfudox** [andrewmackrodt/dockerfiles#7]
Its some days i'm using the 7.2 image in my Gitlab pipeline, with no problem, but today i'm getting this error.

I've seen the image has been updated around 14hrs ago (Apr 2, 2021), so maybe something relevant is changed.

![image](https://user-images.githubusercontent.com/9081531/113424160-f4d44f00-93cf-11eb-9fa5-5003315774c7.png)

**Comment by andrewmackrodt** [comment]
Unfortunately I think this is due to rate limiting on DockerHub's free plan.
